CREATE TABLE BIBLIOTECA (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    code VARCHAR(10) UNIQUE,
    credits INT DEFAULT 20
);

CREATE TABLE LIBRO_ISBN (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    isbn VARCHAR(5) UNIQUE,
    title VARCHAR(50),
    author VARCHAR(50),
    credits INT DEFAULT 0
);

CREATE TABLE LIBRO (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    isbn VARCHAR(5),
    code VARCHAR(10) UNIQUE,
    status BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (ISBN) REFERENCES LIBRO_ISBN(isbn)
);

CREATE TABLE BIBLIOTECA_LIBRO (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    biblioteca_code VARCHAR(10),
    libro_code VARCHAR(10),
    CONSTRAINT UC_LIBRO UNIQUE (biblioteca_code,libro_code),
    FOREIGN KEY (biblioteca_code) REFERENCES BIBLIOTECA(code),
    FOREIGN KEY (libro_code) REFERENCES LIBRO(code)
);

CREATE TABLE PRESTAMO (

    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    biblioteca1 varchar(10),
    biblioteca2 varchar(10),
    librocode varchar(10),
    lenddate TIMESTAMP WITH TIME ZONE,
    returndate TIMESTAMP WITH TIME ZONE
);